import mongoose from "mongoose";
const BookingSchema = new mongoose.Schema({
  UserId:{
    type:String,
    required:true,
  },
  AdminId:{
    type:String,
    required:true,
  },
  RoomId:{
    type:String,
    required:true,
  },
  ImageUrl:{
    type:String,
    required:true,
  },
  RoomNumber:{
    type:String,
    required:true,
  },
  SquareFeet:{
    type:String,
    required:true,
  },
  Floor:{
    type:String,
    required:true,
  },
  NumberOfBeds:{
    type:String,
    required:true,
  },
  MinStay:{
    type:String,
    required:true,
  },
  MaxStay:{
    type:String,
    required:true,
  },
  R_ContactNumber:{
    type:String,
    required:true,
  },
  NormalRent:{
    type:String,
    required:true,
  },
  DateByPrice:[{
    id:String, Date:String,DateByPrice:String
   }],
  R_Description:{
    type:String,
    required:true,
  },
  HouseName:{
    type:String,
    required:true,
  },
  HouseOwnerName:{
    type:String,
    required:true,
  },
  HouseOwnerNumber:{
    type:String,
    required:true,
  },
  Address:{
    type:String,
    required:true,
  },
  City:{
    type:String,
    required:true,
  },
  H_Description:{
    type:String,
    required:true,
  },
  U_ContactNumber:{
    type:String,
    required:true,
  },
  U_Name:{
    type:String,
    required:true,
  },
  FromDate:{
    type:String,
    required:true,
  },
  TillDate:{
    type:String,
    required:true,
  },
  NumberOfPeoples:{
    type:String,
    required:true,
  }
});

export default mongoose.model("Booking", BookingSchema)